import random

# 1. Sum of digits
number = input("Enter number: ")

def sum_digits(number):
    if len(number) == 1 :
        return int(number)
    else:
        return  int(number[0])+sum_digits(number[1:])
print(sum_digits(number))

# 2. is symmetric list [1,2,3,2,1]

n = (input("Enter numbers "))
list_of_numbers = n.split(',')
print(list_of_numbers)

def is_symmetric(list_of_numbers):

        if len(list_of_numbers)<=1 :
            return True
        if list_of_numbers[0] != list_of_numbers[-1]:
            return False
        return is_symmetric(list_of_numbers[1:-1])

print(is_symmetric(list_of_numbers))

#3. Cows and Bulls
print("It's game to guess number generated by computer")
n = int(input("Enter quantity of digits in the number "))
digit = random.sample(range(10), n)

def generate_number(n):
    i = 0
    number = ""
    while True:
        number = number + str(digit[i])
        i +=1
        if i>n-1:
            break
    return number

number = generate_number(n)
print(number)

def cows_count(number, user_num, cows):
    if len(number) == 0:
        return cows
    else:
        if int(number[0]) == int(user_num[0]):
            cows+=1
        return cows_count(number[1:], user_num[1:], cows)

def bulls_count(number, user_num, bulls):
    if len(user_num) == 0:
        return bulls
    else:
        if user_num[0] in number:
            bulls+=1
        return bulls_count(number, user_num[1:], bulls)


def game(attempts):
    user_num = input(f"Try to guess {n}-digit number without replicated digits: ")

    cows = cows_count(number, user_num, 0)
    bulls = bulls_count(number, user_num, 0)

    print("Cows:", cows)
    print("Bulls:", bulls)

    if cows == n:
        print(f"Congratulations! You guessed the number in {attempts} attempts")
        return
    else:
        game(attempts + 1)

game(1)

