import random
import math

# Завдання 1
# Користувач вводить висоту трикутника і символ для заповнення. Програма повинна вивести трикутник, вирівняний по правому краю.
# Приклад введення:
# Введіть висоту: 4.
# Введіть символ: $.

# $
# $$
# $$$
# $$$$

h = int(input("Enter height of triangle "))
c = input("Enter char ")
for i in range(1, h+1):
    print(c*i)

# Завдання 2
# Користувач вводить розміри дошки (ширину і висоту) і два символи для клітинок. Програма повинна відобразити
# шахову дошку, використовуючи ці символи.

width = int(input("Enter width "))
height = int(input("Enter height "))
c1 = input("Enter c1 ")
c2 = input ("Enter c2 ")

for i in range(width):
    for j in range(height):
        if i %2 != 0:
            if j %2 !=0:
                print(c1, end = "\t")
            else:
                print(c2,  end = "\t")
        else:
            if j %2 !=0:
                print(c2,  end = "\t")
            else:
                print(c1,  end = "\t")
    print()

# Завдання 3
# Програма випадковим чином загадує чотиризначне число без цифр, що повторюються. Користувач повинен
# спробувати вгадати це число, вводячи свої варіанти. Після кожного введення програма повідомляє:
# Кількість цифр, які стоять на своїх місцях (бики).
# Кількість цифр, які є в числі, але стоять не на своїх місцях (корови).

print("It's game to guess 4-digit number generated by computer")
digit = random.sample(range(10), 4)

i = 0
number = ""
while True:
    number = number + str(digit[i])
    i +=1
    if i>3:
        break

print(number)
user_num = input("Try to guess 4-digit number without replicated digits, enter your variant ")

bulls = 0
cows = 0
count = 0
for i in user_num:
    if i == number[count] :
        bulls +=1
    else:
        cows +=1
    count +=1
print("You've guessed: ", bulls)
print("Wrong: ", cows)
if bulls == 4:
    print("Congratulations!!! You've guessed the number!")


# Завдання 4
# Число Армстронга — це число, яке дорівнює сумі своїх цифр, піднесених до степеня, що дорівнює кількості цифр.
# Напишіть програму, яка:
# Приймає одне число від користувача.
# Перевіряє, чи є воно числом Армстронга.
# Виводить відповідний результат.
# Приклади чисел Армстронга:

number = input("Enter number ")
count = 0
sum_of_digits = 0
for i in number:
    count+=1
for i in number:
    sum_of_digits = sum_of_digits + int(i)**count
if number == str(sum_of_digits):
    print(f"It is Armstrong's number {number} = {sum_of_digits}")
else:
    print(f"It is NOT Armstrong's number {number} != {sum_of_digits}")


# Завдання 5
# Користувач вводить висоту ромба (непарне число) і символ для заповнення. Програма повинна вивести заповнений ромб.
# Приклад введення:
# Введіть висоту: 5.
# Введіть символ: #.

#
###
#####
###
#

h = int(input("Enter height of diamond (odd number) "))
d = math.ceil(h / 2)
c = input("Enter char to fill ")
char = 0

for i in range(1, h+1):
    if i <= d:
        char = (2*i-1)
        print(char*c)
    else:
        char = char -2
        print(char*c)

# Завдання 6
# Користувач вводить висоту ромба (непарне число) і символ для заповнення. Програма повинна вивести порожнистий ромб.
# Приклад введення:
# Введіть висоту: 7.
# Введіть символ: #.

h = int(input("Enter height of diamond (odd number) "))
d = math.ceil(h / 2)
c = input("Enter char to fill ")

for i in range(1, h+1):
    for j in range(1, h+1):
        if  i <= d:
            if (i == 1 or i == h) and j == d:
                print(c, end = "")
            elif j == (d - i + 1) or j == (d + i -1):
                print(c, end = "")
            else:
                print(" ", end = "")
        else:
            if j == i - d + 1 or j == h - i + d:
                print(c, end = "")
            else:
                print(" ", end = "")
    print()

